global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Scrape configs
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node_exporter
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - node-exporter-vimal:9100

# Alertmanager settings
rule_files:
  - "/usr/mware/prometheus/alert.rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-vimal:9093
      scheme: http
      timeout: 10s
      api_version: v1
